version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    image: api-gateway 
    ports:
      - "8088:8088"
    deploy:
      resources:
        limits:
          memory: 500M
    networks:
      - ptit-net
    restart: always

networks:
  ptit-net:
    external:
      name: ptit-net
