version: "3.8"
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8088:8088"
    networks:
      - iotlab_network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_URI=http://eureka-service:8761/eureka/

  eureka-service:
    image: your-dockerhub-repo/eureka-service:1.0
    container_name: eureka-service
    ports:
      - "8761:8761"
    networks:
      - iotlab_network

networks:
  iotlab_network:
    driver: bridge
