version: '3.8'

services:
  user-service:
    build:
      context: .  # Đảm bảo context đúng để Dockerfile được sử dụng trong cùng thư mục
    container_name: user-service
    image: user-service:latest  # Đặt tên image duy nhất
    ports:
      - "8081:8081"
    networks:
      - ptit-net
    restart: always
    environment:
      - JWT_KEY=${JWT_KEY}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BREVO_API_KEY=${BREVO_API_KEY}
    depends_on:
      - postgres

  postgres:
      image: postgres:14
      container_name: postgres
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: iot_lab
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
networks:
  ptit-net:
    driver: bridge
