server:
  port: 8088
  address: 0.0.0.0

spring:
  application:
    name: API-GATEWAY
    cloud:
        gateway:
          globalcors:
            add-to-simple-url-handler-mapping: true

gateway:
  valid-token-url: ${VALID_TOKEN_URL}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
