server:
  port: ${PORT:8086}

spring:
  mvc:
    dispatch-options-request: true
  application:
    name: STORAGE-SERVICE
    environment: ${ENVIRONMENT:DEV}
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB    # Giới hạn dung lượng file đơn lẻ
      max-request-size: 200MB  # Giới hạn dung lượng toàn bộ yêu cầu (bao gồm tất cả các tệp)
      file-size-threshold: 10KB # Kích thước tối thiểu của file trước khi tạm lưu vào bộ nhớ

storage:
  location: E:/workspace/Do_An/uploads

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

telegram:
  chatId: ${TELEGRAM_CHAT_ID:-1000000000}
  apiToken: ${TELEGRAM_API_TOKEN:-0000000000:XXXXXXXXXXXXXXXXXXXXXXXX}
debug: ${DEBUG:true}
async:
  config:
    core-pool-size: ${ASYNC_CORE_POOL_SIZE:3}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}


