server:
  port: 8088

spring:
  application:
    name: API-GATEWAY
    cloud:
        gateway:
          globalcors:
            add-to-simple-url-handler-mapping: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
