server:
  port: 8081
  address: 0.0.0.0
  servlet:
    context-path: /user

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 hours in milliseconds

refresh-token:
  expiration: 864000000
  key: ${REFRESH_TOKEN_KEY}

spring:
  mvc:
    dispatch-options-request: true
  application:
    name: USER-SERVICE
    environment: ${ENVIRONMENT}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: ${DB_CONNECTION_TIMEOUT}
      maximum-pool-size: ${DB_MAX_POOL_SIZE}
      max-lifetime: ${DB_MAX_LIFETIME}
  jpa:
    show-sql: ${DEBUG}
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: ${DEBUG}
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true
      file-size-threshold: 2KB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/auth/oauth2/callback/google"
            scope:
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
            scope:
              - email
              - public_profile

  # RabbitMQ settings
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# User Service RabbitMQ Configuration
user:
  exchange: user.exchange
  created:
    queue: user.created.queue
    routing:
      key: user.created
  login:
    exchange: user.login.exchange
    queue: user.login.queue
    routing:
      key: user.login.routing.key

debug: ${DEBUG}

async:
  config:
    core-pool-size: ${ASYNC_CORE_POOL_SIZE}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health

ptit:
  storage-service: ${STORAGE_SERVICE}

brevo:
  api:
    key: ${BREVO_API_KEY}
  sender:
    email: ${BREVO_SENDER_EMAIL}
    name: ${BREVO_SENDER_NAME}

# Cấu hình actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
