server:
  port: 8086
  address: 0.0.0.0
  servlet:
    context-path: /storage

spring:
  mvc:
    dispatch-options-request: true
  application:
    name: STORAGE-SERVICE
    environment: ${ENVIRONMENT}
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB
      file-size-threshold: 10KB

storage:
  location: ${STORAGE_LOCATION}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO

debug: ${DEBUG}
async:
  config:
    core-pool-size: ${ASYNC_CORE_POOL_SIZE}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    health-check-url-path: /actuator/health

ptit:
  storage-service: ${STORAGE_SERVICE}

  # Cấu hình actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
